/*******************************************************************************
 * Written 2013 by Per Fahlén, Sweco Postion
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Affero General Public License
 * which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/agpl-3.0.html
 ******************************************************************************/

package org.oemap.services.beans;

import java.util.List;

import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToMany;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.xml.GeneratedElementable;
import se.unlogic.standardutils.xml.XMLElement;

/**
 * 
 * @author Per Fahlén - Sweco Position AB Bean for grouplayer in oemapadmin
 */

@XMLElement
@Table(name = "oemapadmin_groupLayers")
public class GroupLayer extends GeneratedElementable {

	@XMLElement
	@Key
	@DAOManaged(autoGenerated = true)
	private Integer groupLayerID;

	@XMLElement
	@DAOManaged
	private String name;

	@XMLElement
	@DAOManaged
	@ManyToMany(linkTable = "oemapadmin_grouplayer_layers")
	private List<Layer> layers;

}
