/******************************************************************************
Copyright Härnösands kommun(C) 2014 

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Affero General Public License
 * which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/agpl-3.0.html
 ******************************************************************************/

package org.oemap.services.beans;

import java.util.List;

import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.ManyToMany;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.xml.GeneratedElementable;
import se.unlogic.standardutils.xml.XMLElement;

/**
 * 
 * @author Per Fahl�n - Sweco Position AB Bean for grouplayer in oemapadmin
 */

@XMLElement
@Table(name = "oemapadmin_groupLayers")
public class GroupLayer extends GeneratedElementable {

	@XMLElement
	@Key
	@DAOManaged(autoGenerated = true)
	private Integer groupLayerID;

	@XMLElement
	@DAOManaged
	private String name;

	@XMLElement
	@DAOManaged
	@ManyToMany(linkTable = "oemapadmin_grouplayer_layers")
	private List<Layer> layers;

}
