package org.oemap.services.beans;

import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.xml.XMLElement;

public class LayerColumn extends ConfigBase {

	@XMLElement
	@Key
	@DAOManaged(autoGenerated = true)
	private Integer layerColumnId;

	@XMLElement
	@DAOManaged
	private String sourceName;

	@XMLElement
	@DAOManaged
	private String sourceId;

	@XMLElement
	@DAOManaged
	private String alias;

	@XMLElement
	@DAOManaged
	private Boolean isSearchable;

	@XMLElement
	@DAOManaged
	private Boolean isVisible;

	@XMLElement
	@DAOManaged
	private Boolean isUrl;

	public Integer getLayerColumnId() {
		return layerColumnId;
	}

	public void setLayerColumnId(Integer layerColumnId) {
		this.layerColumnId = layerColumnId;
	}

	public String getSourceName() {
		return sourceName;
	}

	public void setSourceName(String sourceName) {
		this.sourceName = sourceName;
	}

	public String getSourceId() {
		return sourceId;
	}

	public void setSourceId(String sourceId) {
		this.sourceId = sourceId;
	}

	public String getAlias() {
		return alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	public Boolean getIsSearchable() {
		return isSearchable;
	}

	public void setIsSearchable(Boolean isSearchable) {
		this.isSearchable = isSearchable;
	}

	public Boolean getIsVisible() {
		return isVisible;
	}

	public void setIsVisible(Boolean isVisible) {
		this.isVisible = isVisible;
	}

	public Boolean getIsUrl() {
		return isUrl;
	}

	public void setIsUrl(Boolean isUrl) {
		this.isUrl = isUrl;
	}
}
