/******************************************************************************
Copyright Härnösands kommun(C) 2014  <name of author>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Affero General Public License
 * which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/agpl-3.0.html
 ******************************************************************************/

package org.oemap.services.beans;

import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.xml.XMLElement;

public class LayerColumn extends ConfigBase {

	@XMLElement
	@Key
	@DAOManaged(autoGenerated = true)
	private Integer layerColumnId;

	@XMLElement
	@DAOManaged
	private String sourceName;

	@XMLElement
	@DAOManaged
	private String sourceId;

	@XMLElement
	@DAOManaged
	private String alias;

	@XMLElement
	@DAOManaged
	private Boolean isSearchable;

	@XMLElement
	@DAOManaged
	private Boolean isVisible;

	@XMLElement
	@DAOManaged
	private Boolean isUrl;

	public Integer getLayerColumnId() {
		return layerColumnId;
	}

	public void setLayerColumnId(Integer layerColumnId) {
		this.layerColumnId = layerColumnId;
	}

	public String getSourceName() {
		return sourceName;
	}

	public void setSourceName(String sourceName) {
		this.sourceName = sourceName;
	}

	public String getSourceId() {
		return sourceId;
	}

	public void setSourceId(String sourceId) {
		this.sourceId = sourceId;
	}

	public String getAlias() {
		return alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	public Boolean getIsSearchable() {
		return isSearchable;
	}

	public void setIsSearchable(Boolean isSearchable) {
		this.isSearchable = isSearchable;
	}

	public Boolean getIsVisible() {
		return isVisible;
	}

	public void setIsVisible(Boolean isVisible) {
		this.isVisible = isVisible;
	}

	public Boolean getIsUrl() {
		return isUrl;
	}

	public void setIsUrl(Boolean isUrl) {
		this.isUrl = isUrl;
	}
}
