/*******************************************************************************
 * Written 2013 by Per Fahlén, Sweco Postion
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Affero General Public License
 * which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/agpl-3.0.html
 ******************************************************************************/

package org.oemap.services.beans.settings;

import se.unlogic.standardutils.dao.annotations.DAOManaged;
import se.unlogic.standardutils.dao.annotations.Key;
import se.unlogic.standardutils.dao.annotations.Table;
import se.unlogic.standardutils.xml.XMLElement;

@Table(name = "oemapadmin_servers")
public class Server extends SettingBase {

	@XMLElement
	@DAOManaged(autoGenerated = true)
	@Key
	private Integer ID;

	@XMLElement
	@DAOManaged
	private String type;

	public Integer getID() {
		return ID;
	}

	public void setId(Integer id) {
		this.ID = id;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}
}
