Ext.application({
	requires: ['Ext.container.Viewport',
	           'AdmClient.controller.Main',
	           'AdmClient.controller.MainToolbar',
	           'AdmClient.controller.MapConfiguration',
	           'AdmClient.controller.Servers',
	           'AdmClient.controller.ToolsGrid',
	           'AdmClient.controller.Layers',
	           'AdmClient.controller.Search',
	           'AdmClient.controller.PreviewMap',
	           'AdmClient.controller.ConfigLayers',
	           'AdmClient.controller.toolDetails.DrawPoint',
	           'AdmClient.controller.toolDetails.DrawPath',
	           'AdmClient.controller.toolDetails.DrawPolygon',
	           'AdmClient.controller.toolDetails.FullExtent',
	           'AdmClient.controller.toolDetails.Print',
	           'AdmClient.controller.toolDetails.Identify',
	           'AdmClient.controller.toolDetails.DetailReport',
	           'AdmClient.controller.toolDetails.MeasureLine',
	           'AdmClient.controller.toolDetails.MeasureArea',
	           'AdmClient.controller.toolDetails.DeleteGeometry',
	           'AdmClient.controller.toolDetails.ModifyGeometry',
	           'AdmClient.controller.toolDetails.SelectGeometry',
	           
	           'AdmClient.store.Servers',
	           'AdmClient.store.ToolStore',
	           'AdmClient.store.Layers',
	           'AdmClient.store.SearchServer',
	           'AdmClient.store.GroupedLayerTree',
	           'AdmClient.store.Municipalities',
	           
               'AdmClient.view.main.MainToolbar',
               'AdmClient.view.Main',
               'AdmClient.view.mapconfiguration.tools.ToolsGrid',
               'AdmClient.view.mapconfiguration.tools.details.General',
               'AdmClient.view.mapconfiguration.tools.details.DrawGeometry',
               'AdmClient.view.mapconfiguration.tools.details.DeleteGeometry',
               'AdmClient.view.mapconfiguration.tools.details.DrawObject',
               'AdmClient.view.mapconfiguration.tools.details.FullExtent',
               'AdmClient.view.mapconfiguration.tools.details.Identify',
               'AdmClient.view.mapconfiguration.tools.details.MeasureArea',
               'AdmClient.view.mapconfiguration.tools.details.MeasureLine',
               'AdmClient.view.mapconfiguration.tools.details.Print',
               'AdmClient.view.mapconfiguration.tools.details.ModifyGeometry',
               'AdmClient.view.mapconfiguration.map.PreviewMap',
               
               'AdmClient.view.mapconfiguration.search.SearchPanel',
               
               'AdmClient.view.MapConfiguration',
               'AdmClient.view.Settings',
               'AdmClient.view.settings.SettingsGridBase',
               'AdmClient.view.settings.GisServersGrid',
               'AdmClient.view.settings.SearchServersGrid',
               'AdmClient.view.settings.Layers',
               'AdmClient.view.about.About',

               'AdmClient.model.Server',
               'AdmClient.model.SettingBase',
               'AdmClient.model.SearchServer',
               'AdmClient.model.Layer',
               'AdmClient.model.Config'
               ],
    name: 'AdmClient',
    appFolder: 'src/main/javascript',
    controllers: ['Main', 
                  'Layers', 
                  'MainToolbar', 
                  'Servers', 
                  'MapConfiguration', 
                  'ToolsGrid', 
                  'Layers', 
                  'Search', 
                  'PreviewMap', 
                  'ConfigLayers',
                  'toolDetails.DrawPoint', 
                  'toolDetails.DrawPath',
                  'toolDetails.DrawPolygon',
                  'toolDetails.FullExtent',
                  'toolDetails.Print',
                  'toolDetails.Identify',
                  'toolDetails.MeasureLine',
                  'toolDetails.MeasureArea',
                  'toolDetails.DeleteGeometry',
                  'toolDetails.ModifyGeometry',
                  'toolDetails.SelectGeometry',
                  'toolDetails.DetailReport',
                ],
    models : ['SettingBase','Server', 'SearchServer', 'Layer', 'Config'],
    launch: function() {
        

    	this.config = Ext.create('AdmClient.model.Config');
        Ext.create('Ext.container.Viewport', {
        	layout: 'border',
//        	height : 800,
        	items : [{xtype: 'main'}]
        });
    }
});
